all: libLcd.a lcddemo.elf

CPU             = msp430g2553
CFLAGS          = -mmcu=${CPU} -Os -I../h 
LDFLAGS 	= -L/opt/ti/msp430_gcc/include -L../lib 
#switch the compiler (for the internal make rules)
CC              = msp430-elf-gcc
AS              = msp430-elf-gcc -mmcu=${CPU} -c
AR              = msp430-elf-ar

libLcd.a: font-11x16.o font-5x7.o font-8x12.o lcdutils.o lcddraw.o
	$(AR) crs $@ $^

lcddraw.o: lcddraw.c lcddraw.h lcdutils.h
lcdutils.o: lcdutils.c lcdutils.h

install: libLcd.a
	mkdir -p ../h ../lib
	mv $^ ../lib
	cp *.h ../h

clean:
	rm -f libLcd.a *.o *.elf

lcddemo.elf: lcddemo.o libLcd.a wdt_handler.o switches.o switches_c.o buzzer.o
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@ -lTimer -lLcd 

load: lcddemo.elf
	msp430loader.sh $^

wdt_handler.o: wdt_handler.s
switches.o: switches.s
switches_c.o: switches_c.c switches.h
buzzer.o: buzzer.c buzzer.h
